steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us.gcr.io/$PROJECT_ID/albionmarket/backend:latest', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us.gcr.io/$PROJECT_ID/albionmarket/backend:$COMMIT_SHA', '.' ]
images:
  - 'us.gcr.io/$PROJECT_ID/albionmarket/backend:latest'
  - 'us.gcr.io/$PROJECT_ID/albionmarket/backend:$COMMIT_SHA'